name: npm

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: null

env:
  DEBUG: napi:*
  MACOSX_DEPLOYMENT_TARGET: '10.13'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: stable - x86_64-apple-darwin - node@18
    permissions:
      contents: write
    env: 
      GH_TOKEN: ${{ github.token }}
    runs-on: macos-15-intel
    steps:
      - name: Fetch denokv repo
        uses: actions/checkout@v4
        with:
          repository: denoland/denokv
          ref: main

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./npm/napi/yarn.lock

      - name: Remove rust-toolchain.toml (conflicts with mac arm64 build)
        run: rm rust-toolchain.toml

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-apple-darwin

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: x86_64-apple-darwin-cargo-macos-15-intel

      - name: Install dependencies
        run: yarn install
        working-directory: ./npm/napi

      - name: Build
        working-directory: ./npm/napi
        shell: bash
        run: |
          brew install protobuf
          yarn build --target x86_64-apple-darwin
          strip -x *.node

      - name: Check linting # needs to run after build so protoc is available
        run: cargo clippy --release --all-targets --all-features -- -D clippy::all
        working-directory: ./npm/napi

      - name: Extract the latest tag
        run: | 
          git fetch --tags
          echo "LATEST_TAG=$(git tag | sort -V | tail -n 1)" >> $GITHUB_ENV

      - name: Release the build
        run: gh release new $LATEST_TAG --repo $GITHUB_REPOSITORY ./npm/napi/deno-kv-napi.darwin-x64.node

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-x86_64-apple-darwin
          path: npm/napi/deno-kv-napi.darwin-x64.node
          if-no-files-found: error
